### ISSUE TITLE
Merge armstro-patch-4 and conform to Git best practices for ZAC meeting admin

### ISSUE THREAD

**Issue by PeterFandelAtRocket** [zowe/zlc#236]
Currently all meeting notes and agendas are located on branch.  It is not the right way to do this.  A ZAC member needs to figure out how it is supposed to be done, merge the history, start doing it in a manner conforming to how Git is intended to be used and pass on the knowledge to rest of ZAC as needed.

**Comment by armstro** [comment]
Done - will use zac slack channel and community github for actions
